<?php

class advisingDataOptionType
{
    const __default = 'ADVISOR_COMMITTEE_RELATIONSHIP';
    const ADVISOR_COMMITTEE_RELATIONSHIP = 'ADVISOR_COMMITTEE_RELATIONSHIP';
    const STUDENT_ADVISOR_RELATIONSHIP = 'STUDENT_ADVISOR_RELATIONSHIP';


}
