<?php

class serviceAlertCodeType
{
    const __default = 'PHOTO_INFORMATION_ALL';
    const PHOTO_INFORMATION_ALL = 'PHOTO_INFORMATION_ALL';
    const PHOTO_INFORMATION_SOME = 'PHOTO_INFORMATION_SOME';
    const ENROLLMENT_DATA_BEFORE_SUMMER_1999 = 'ENROLLMENT_DATA_BEFORE_SUMMER_1999';
    const ENROLLMENT_DATA_ACCESS_ERROR = 'ENROLLMENT_DATA_ACCESS_ERROR';
    const BUILDING_DETAILS_SERVICE_ERROR = 'BUILDING_DETAILS_SERVICE_ERROR';


}
