<?php

namespace edu\wisc\services\caos;

class studentDataOptionType
{
    const __default = 'ACADEMIC_OBJECTIVE';
    const ACADEMIC_OBJECTIVE = 'ACADEMIC_OBJECTIVE';
    const ADVISOR_RELATIONSHIPS = 'ADVISOR_RELATIONSHIPS';
    const AFFILIATIONS = 'AFFILIATIONS';
    const CREDIT_TOTALS = 'CREDIT_TOTALS';
    const DIRECTORY = 'DIRECTORY';
    const ENROLLMENT = 'ENROLLMENT';
    const ENROLLMENT_WITH_DROPS = 'ENROLLMENT_WITH_DROPS';
    const ENROLLMENT_IMPACTS = 'ENROLLMENT_IMPACTS';
    const ENTRY_INFORMATION = 'ENTRY_INFORMATION';
    const PHOTO_INFORMATION = 'PHOTO_INFORMATION';
    const ACADEMIC_SUMMARY = 'ACADEMIC_SUMMARY';
    const RESIDENCY = 'RESIDENCY';
    const SECONDARY_SCHOOL = 'SECONDARY_SCHOOL';
    const TRANSFER_CREDIT = 'TRANSFER_CREDIT';
    const TEST_SCORES = 'TEST_SCORES';


}
